package com.tut.hibernate;

// Generated Feb 21, 2014 11:05:34 AM by Hibernate Tools 3.4.0.CR1

/**
 * Attachment generated by hbm2java
 */
public class Attachment implements java.io.Serializable {

	private Integer id;
	private String identifier;
	private String name;
	private String type;

	public Attachment() {
	}

	public Attachment(String identifier, String name, String type) {
		this.identifier = identifier;
		this.name = name;
		this.type = type;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getIdentifier() {
		return this.identifier;
	}

	public void setIdentifier(String identifier) {
		this.identifier = identifier;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
