package com.tut.hibernate;

// Generated Feb 20, 2014 12:01:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CurrUploads generated by hbm2java
 */
public class CurrUploads implements java.io.Serializable {

	private Integer id;
	private String identifier;
	private int progress;
	private String status;
	private Date dateAdded;

	public CurrUploads() {
	}

	public CurrUploads(String identifier, int progress, String status,
			Date dateAdded) {
		this.identifier = identifier;
		this.progress = progress;
		this.status = status;
		this.dateAdded = dateAdded;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getIdentifier() {
		return this.identifier;
	}

	public void setIdentifier(String identifier) {
		this.identifier = identifier;
	}

	public int getProgress() {
		return this.progress;
	}

	public void setProgress(int progress) {
		this.progress = progress;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

}
